### ISSUE TITLE
Can't download pretrained weights from aws

### ISSUE THREAD

**Issue by jhhan45** [vt-vl-lab/tf_flownet2#13]
I completed the compile and I try to download the pretrained weights using download.sh
But ERORR 404: NOT FOUND is occurred.
https://s3.us-east-2.amazonaws.com/flownetdata/weights.tar.gz is not working. 
How can I solve it? or get the weights?
Thanks.

**Comment by Yuliang-Zou** [comment]
Seems that the file has been deleted. I can upload mine to somewhere. This might take around one week since I am not out of campus.

**Comment by chenrxi** [comment]
could you please send to my email ruoxi16@mail.ustc.edu.cn. Thank you very much!

**Comment by Yuliang-Zou** [comment]
Please use this [backup](https://github.com/sampepose/flownet2-tf/issues/62#issuecomment-441055492)
