### ISSUE TITLE
logic for dealing with different input size

### ISSUE THREAD

**Issue by wfchen-umich** [vt-vl-lab/tf_flownet2#4]
Hi, 
Thanks for this nice piece of code. 
Can you pinpoint me to the part where you deal with different image resolutions? What's your strategy? Thanks.

**Comment by Yuliang-Zou** [comment]
Hi @wfchen-umich , I crop the feature map before skip connection. The function is defined [here](https://github.com/vt-vl-lab/tf_flownet2/blob/master/FlowNet2_src/utils.py#L46),  and you can see how I used it in the network definition file (i.e., [this](https://github.com/vt-vl-lab/tf_flownet2/blob/master/FlowNet2_src/flownet_s/flownet_s.py#L62))
