### ISSUE TITLE
why my outputting is something different from yours?

### ISSUE THREAD

**Issue by Timthony** [vt-vl-lab/tf_flownet2#7]

**Comment by Timthony** [comment]
and each output is different

**Comment by Yuliang-Zou** [comment]
Can you describe the differences?

**Comment by Timthony** [comment]
![](https://ws3.sinaimg.cn/large/006tNbRwly1fwotp1pclcj30hs0dcdko.jpg)    
![](https://ws3.sinaimg.cn/large/006tNbRwly1fwotpd3p6rj30hs0dc40p.jpg)    
These are the results of two runs.  The code has not been modified, directly to the clone.

**Comment by Yuliang-Zou** [comment]
Can you tell me your TF version? This code should be able to run under tf1.2.0

**Comment by Timthony** [comment]
tensorflow-gpu(Version 1.2)，ubuntu16.04，pycharm

**Comment by Timthony** [comment]
> Can you tell me your TF version? This code should be able to run under tf1.2.0

My environment tensorflow-gpu(Version 1.2)，ubuntu16.04，pycharm

**Comment by Timthony** [comment]
Please yours weights(4.4g) are same to the repo(sampepose/flownet2-tf)?

> Can you tell me your TF version? This code should be able to run under tf1.2.0

https://github.com/vt-vl-lab/tf_flownet2/issues/7#issuecomment-433775092

> Can you tell me your TF version? This code should be able to run under tf1.2.0

Please yours weights are same to the repo(sampepose/flownet2-tf)?

**Comment by Timthony** [comment]
大哥，有时间帮忙想一下哈

**Comment by Yuliang-Zou** [comment]
GPU type? Did you modify [this line](https://github.com/vt-vl-lab/tf_flownet2/blob/master/Makefile#L13) according to your GPU?

**Comment by Timthony** [comment]
> GPU type? Did you modify [this line](https://github.com/vt-vl-lab/tf_flownet2/blob/master/Makefile#L13) according to your GPU?

No,but i don't know how to change it.I'll try it.Thank you very much.

**Comment by OwalnutO** [comment]
Same problem. Solved by changing that line according to your GPU.
For the GPU information you needed, please refer:
https://blog.csdn.net/u010290301/article/details/81189803
